### ISSUE TITLE
Dropdown - Section Headline

### ISSUE THREAD

**Issue by kazaky** [adevinta/spark-android#1038]
Add an item that have the style for the section headline in normal and highlight mode for consumers to use in case they're present in their designs.

<table>
<tr>
 <td> Normal
 <td> Highlight
<tr>
 <td><img width="657" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/a8ffc7c5-513b-4855-b8b8-f343a93432d2">
 <td><img width="673" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/a99ec579-452e-4584-97e0-a2e501986545">
<tr>
<td>`body2` in `onSurface` dim1
<td>`body1.highlight` in `onSurface` dim1
</table>

both of them with 16.dp in horizontal padding and 8.dp in vertical

**Comment by soulcramer** [comment]
Done in #1150
