### ISSUE TITLE
Bottosheet landscape: content of the page overflows below the Bottomsheet

### ISSUE THREAD

**Issue by kazaky** [adevinta/spark-android#1039]
> on mobile / landscape, content of the page overflows below the bottomsheet. IMO this should be fixed before release it.

As discovered by @elisa-hery during QA
https://github.com/adevinta/spark-android/issues/1039#issue-2213401631

![image](https://github.com/adevinta/spark-android/assets/4202132/e359443d-1b9a-419d-b1ce-bd2dd5445f81)

**Comment by soulcramer** [comment]
We'll have to wait this [issue](https://issuetracker.google.com/issues/274872542) to be closed to check if this is fixed or not

**Comment by soulcramer** [comment]
Fixed with version 1.3 of Material 3
