### ISSUE TITLE
[Component] Snackbar

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#1075]
```[tasklist]
### Tasks
- [x] Add new intents
- [x] Add documentation
- [x] Add tests
- [x] Add examples & Configurator
```
https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=43448-28057&mode=design&t=dnqzsyTqPaMOTeui-0

**Comment by elisa-hery** [comment]
Snackbar does not work, I can't even open it. I'm moving it back to "in progress"

**Comment by kazaky** [comment]
@elisa-hery I confirm,
It was working normally, must be due to recent changes in Catalog app,
I will investigate

**Comment by kazaky** [comment]
@elisa-hery Fixed here https://github.com/adevinta/spark-android/pull/1197

**Comment by thomas-leguellec** [comment]
@JeremiasUX @ChrisDesignOps @Bibisirius Can you sync to test it asap please?

**Comment by JeremiasUX** [comment]
I discovered two issues:

- Both actions have a different press background color, let's align them. 
- Border tokens does not match with the official spark tokens (will be discussed on the 03.07)

<picture>
 <img alt="description" src="https://github.com/adevinta/spark-android/assets/139337913/f2520146-c783-42c1-a2de-9634396a5d1c" width="200px">
</picture>
<picture>
 <img alt="description" src="https://github.com/adevinta/spark-android/assets/139337913/079f6a9b-ef3f-4da2-ad69-3db068d0d61d" width="200px">
</picture>
