### ISSUE TITLE
[Bug]: Text field placeholder is invisible when not focused

### ISSUE THREAD

**Issue by Sildian** [adevinta/spark-android#1095]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

Other (please specify it)

### 🐛 What happened?

Hi,

I'm using the TextField with a placeholder attribute and I've realized that the placeholder text is visible only when the field is focused, remaining invisible otherwise.

![Text field focused](https://github.com/adevinta/spark-android/assets/47478612/3d571636-6d9e-4ba3-9427-a12f7011ac5d)
![Text field not focused](https://github.com/adevinta/spark-android/assets/47478612/0c852e53-1fb3-414d-8682-ad7558088b65)

(To be more accurate, I'm using MultilineTextField, but maybe the bug applies to all versions of TextField)

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
```

**Comment by kazaky** [comment]
Hi @Sildian After investigating the issue and talking with Spark designers.

You must provide a label for any TextField component,
also this is for Accessibility reasons (It's better on TalkBack)

By doing so, this shall resolve your issue.

Thanks for reporting
