### ISSUE TITLE
Add new KA Theme colors for Dark Theme party

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#1121]
```[tasklist]
### Tasks
- [x] Add new colors to catalog app
- [x] Add new colors to Polaris
```

**Comment by elisa-hery** [comment]
@soulcramer does it need to be tested by designers ? 👀

**Comment by elisa-hery** [comment]
No need to approve the PR from design side https://adevinta.slack.com/archives/C04LNCEMMUN/p1718718781205299?thread_ts=1718713488.330569&cid=C04LNCEMMUN i'm moving it to done !
