### ISSUE TITLE
BottomSheet display content bellow the system bar even when edge-to-edge is not active

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#1142]
As reported [here](https://adevinta.slack.com/archives/C04QQEU3Y2H/p1716999254230699) the BottomSheet doesn't take into account the windowInset.

![image](https://github.com/adevinta/spark-android/assets/11772084/cdd1c650-2d06-445e-9409-346d3286c69b)
![image](https://github.com/adevinta/spark-android/assets/11772084/7216965b-4bcd-4a63-8a8f-182f3b683d10)

**Comment by thomas-leguellec** [comment]
https://adevinta.slack.com/archives/C04QQEU3Y2H/p1716999254230699

**Comment by soulcramer** [comment]
I replicate it on Spark Catalog app with E2E disabled.
The next version of Material does [fix this issue](https://issuetracker.google.com/issues/305565075) (and many others like the first one I mentioned in the thread).
What should we do now as this is something we can’t fix on our side as the root cause is [Material](https://issuetracker.google.com/issues/274872542#comment18) using a Popup impl to display the BottomSheet and they changed it to a Dialog impl in the next version to solve all their issues.


https://github.com/adevinta/spark-android/assets/11772084/2f27a9cd-cab1-4aab-a8d0-f454b703924b


https://github.com/adevinta/spark-android/assets/11772084/4b115843-ce11-46a5-bcd3-ddb3defbe9ce

**Comment by soulcramer** [comment]
We need to wait for M3 v1.3.0 to have this issue fixed
