### ISSUE TITLE
[Textfield] Textfield on 0.11.0 have a offset pushing their addons to the bottom

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#1243]
As seen in the bellow image 
![image](https://github.com/user-attachments/assets/096318a9-1054-478f-bf93-6f7b9083c4ca)

Addons are pushed to the bottom side

**Comment by elisa-hery** [comment]
hey @soulcramer some remarks after testing : 
1. when state message is multiline, the input grows the same size 

<picture>
  <img alt="specs" src="https://github.com/user-attachments/assets/633784a1-2adb-43e9-9875-ca056d399a05" width="500px">
</picture>

2. when the textfield is disabled, the icon button is still clickable 

https://github.com/user-attachments/assets/6e0ba777-bb1e-447d-8805-d4dea6c3fde4


3. I don't manage to see the placeholder : there is always either a value or a label, is it normal ?

4. a11y : when activating talkback, I hear _"modification en cours - [value] - zone de modification - [helper message]"_ but the label is not read. Is it normal ? 

5. in the examples, textfields are not editable

**Comment by soulcramer** [comment]
I fixed 1, 3, 5 in the version 0.11.2;

for 2 we can't disbale addons as we can't access their api from the Textfield so it's up to the devs to disable both of them at the same time.

for 4 I hope I'll be able to solve the a11y issues in the (soonTM) version 1.3 of M3

**Comment by elisa-hery** [comment]
Ok that's perfect @soulcramer  ✅ 

Images of the fixes : 
1. the input height does not grow anymore with the height of the helper text : 
<img width="728" alt="Screenshot 2024-09-05 at 10 46 10" src="https://github.com/user-attachments/assets/bd791615-0dff-4e57-b200-4446252c2999">


3. we can see the placeholder if any

<img width="723" alt="Screenshot 2024-09-05 at 10 44 40" src="https://github.com/user-attachments/assets/f93021c8-b971-4489-92ee-84d78e2f67c3">
