### ISSUE TITLE
Requirements to publish on Maven Central

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#14]
- Find who own the maven credentials that are used to sign the artifacts (maybe this is the one? https://issues.sonatype.org/browse/OSSRH-70883)
- then we need the
  - GPG key, GPG password to sign the published atirfacts
  - Username & Token [OSSRH (_Open Source Project Repository Hosting_)](https://central.sonatype.org/publish/release/) to identify in what repository we publish them

**Comment by SimonMarquis** [comment]
I received the necessary credentials.
- Next steps: #4
