### ISSUE TITLE
Select a bot to handle gradle dependences update

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#16]
Dependabot or Renovate?

@andresin87, @SimonMarquis did a request to setup renovate on the repo, is it okay to use it instead of Dependabot?

**Comment by andresin87** [comment]
for me its ok, but i did not received any request

**Comment by SimonMarquis** [comment]
Hi @andresin87, here is what I have on https://github.com/apps/renovate/installations/new

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1921278/217597773-5b3960b2-de73-49f6-ad92-046fdc70d088.png">

**Comment by SimonMarquis** [comment]
Also, @dependabot does not currently support Gradle's version catalog feature that we rely on.
https://github.com/dependabot/dependabot-core/pull/6249

**Comment by soulcramer** [comment]
Since we've selected Renovate the next step will be in #99
