### ISSUE TITLE
Add commit linter (commitizen) in CI?

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#19]
- [ ] Ask other plateforms why/how they're using it

Maybe add a local GA?

**Comment by SimonMarquis** [comment]
There are no official port of https://commitizen-tools.github.io/commitizen/ on GitHub Actions.
Also, there is currently no easy way provided by GitHub to enforce the resulting PR squashed commit message. So we could only check for instance if the PR title follows a convention, and hope the user does not modify the resulting merge commit.

**Comment by SimonMarquis** [comment]
Custom workflow has been set up to check PR titles https://github.com/adevinta/spark-android/actions/workflows/pr-title-format.yml

Do you thinkg this is enough for now, and can we close this issue?

**Comment by soulcramer** [comment]
Yes we can close its good enough for now imo 🤔 
On monday we'll discuss on what process we want for the chapter to contribute/review on this project so we might have to adjust a few things after that
