### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#20]
Discuss what we want to put in this with the team first

**Comment by SimonMarquis** [comment]
This document should contain instructions on how to setup git lfs (to correctly work with snapshot testing infrastructure).
Something like

### [git-lfs](https://git-lfs.com/)

This repository uses [cashapp/paparazzi](https://github.com/cashapp/paparazzi) for screenshot testing purposes.  
If you introduce visible changes, you'll likely have to update screenshots files for the test to pass.

```bash
# Install
brew install git-lfs
# Check
git lfs install
```

**Comment by soulcramer** [comment]
Agreed, from what I saw on circuit they even have a hook to notify the contributors that they need to set it up 👍 
https://github.com/slackhq/circuit/blob/8139707c206c2aff6fca15fc968d6a06563baf87/config/git/hooks/pre-receive

**Comment by SimonMarquis** [comment]
In fact, they use https://github.com/ActionsDesk/lfs-warning in their workflow

https://github.com/slackhq/circuit/blob/d36a65fd06cad769fa1596596c443c7ca9daf6a5/.github/workflows/ci.yml#LL35-L36C43

**Comment by SimonMarquis** [comment]
Let's see how this behaves in #52

**Comment by SimonMarquis** [comment]
Can we close this issue?
