### ISSUE TITLE
Add a mapping documentation to help migration from Brikke to Spark

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#207]
We can reuse the one made by the web team

**Comment by thomas-leguellec** [comment]
Prerequisite: Mathieu needs to furnish the mapping colors

**Comment by soulcramer** [comment]
Blocked by #215

**Comment by thomas-leguellec** [comment]
Discussion last week: we need that the designers to a mapping documentation between Brikke and Spark
