### ISSUE TITLE
Enable Git LFS

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#22]
We will need this to have better screenshot testing with paparazzi for #7 
We used these to inspire ourselves for these tests:
- https://github.com/DroidKaigi/conference-app-2022/pull/97/files
- https://github.com/slackhq/circuit/pull/204/files

**Comment by SimonMarquis** [comment]
Documentation: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github

**Comment by SimonMarquis** [comment]
@soulcramer Can you confirm me the expected locations of these images in our repo?
They mention `**/snapshots/**/*.png`

Also, we might as well add CI checks for that.

**Comment by SimonMarquis** [comment]
By the way, what is the workflow for snapshot testing?
Should they always run on PRs? And who is responsible for generating the golden images? (the CI, or the local machine of the dev)

**Comment by soulcramer** [comment]
Yes this is the correct path.

> By the way, what is the workflow for snapshot testing?
I think we will stay with the workflow we were using until now: The test run on every PR and fail the PR if its fail, wait for the screenshot to be regenerated in the PR  by the dev.

Ultimately it would be ideal imo that the CI is responsible of that since with our current process nothing can stop the dev from uploading new screenshots when uploading his first patchset which would make this test unnecessary 😞

**Comment by SimonMarquis** [comment]
Ok, we'll have to work on a custom workflow then, because it's not very clear to me what should be executed and when it should be or not.
