### ISSUE TITLE
Build our own layout + navigation and show the **Showcase** previews with the help of the metadata

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#220]

**Comment by SimonMarquis** [comment]
If we build our own layout/navigation, we should remove the Showkase plugin right?

**Comment by soulcramer** [comment]
I don't know, can we still get the metadata without the plugin? if so there's no problem with removing it for this issue.
Anyway we will be going away from Showkase in the future 👍

**Comment by SimonMarquis** [comment]
It depends if we really benefit from this "metadata" to be honest, I don't really know what it contains, but I'm pretty sure we could replace it with minimal effort.
