### ISSUE TITLE
Be able to select from multiple theme in the demo app

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#222]

**Comment by SimonMarquis** [comment]
We could take inspiration from Google's material catalog:

https://play.google.com/store/apps/details?id=androidx.compose.material.catalog&hl=en&gl=US

They already have a nice UI to configure the displayed theme and colors

![image](https://user-images.githubusercontent.com/1921278/223069921-bce57336-edfe-4392-b5ed-3b43f30077bd.png)

**Comment by soulcramer** [comment]
Yep I was going to propose it 😋
