### ISSUE TITLE
Bundle the lint rules in the artifact 

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#24]
We need to verify how does this work when imported into LBC as we also plan to use the [slak-compose](https://github.com/slackhq/compose-lints) lints too:
- If this is used in LBC, is it applied only on the modules that use it?
- or applied also on the modules that depends on the one that use it?
- or on every modules from the project?

**Comment by SimonMarquis** [comment]
I suppose it applies to all modules where lint is also applied as soon as this lint is included in the compilation classpath.
