### ISSUE TITLE
Select where we want to host the technical documentation

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#25]
Currently we have a batch of makrdown files listed at the root of this project, we need to decide how to distribute them.
We can either let them here, use a tool like backstage (can we?) or use github pages for starter.
I was also thinking if we want to use github pages to host our kdoc 🤔

**Comment by SimonMarquis** [comment]
IMO, the technical documentation would be more helpful in GitHub pages than the Dokka pages since we can already see them in the javadoc (as a consumer of the library).
Also, it might be possible to host the Dokka pages inside a mkdocs site.

**Comment by soulcramer** [comment]
Yop!
Are we agreeing on this ?
 - We'll use Github fro the technical documentation like we did previously for now.
 - We'll use Github pages to host the Dokka doc
 - All of those docs will be linked in the Zeroheight when it'll be available

**Comment by SimonMarquis** [comment]
> - We'll use Github fro the technical documentation like we did previously for now.

Do you mean having documentation on how to use a Spark button and all their variants in [spark/docs/Button.md](spark/docs/Button.md)?

If so, I agree 💯 %
