### ISSUE TITLE
[Tech] Use the new Coil 2.3.0 `FakeImageLoaderEngine` api for testing

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#326]
>Introduce a new coil-test artifact, which includes FakeImageLoaderEngine. This class is useful for hardcoding image loader responses to ensure consistent and synchronous (from the main thread) responses in tests. See [here](https://coil-kt.github.io/coil/testing) for more info.

We're blocked since we have to wait for https://github.com/adevinta/spark-android/pull/281 to be merged first.

We can use `FakeImageLoaderEngine` for our previews currently and maybe our demo app as well?

**Comment by SimonMarquis** [comment]
We are currently using version 2.5.0 and the test artifact is available.
Although, I'm not sure why we would use it in this project, since we can already fake the input in screenshot tests.
@soulcramer should we close this, or did you have something specific in mind?
