### ISSUE TITLE
[FR]: Complete README for basic install

### ISSUE THREAD

**Issue by AliceBarsseLbc** [adevinta/spark-android#378]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

After cloning the project, a basic `./gradlew :tasks` shows that there is `installDebug` task. However, if you run `./gradlew installDebug` initially it will not work. The error is:
```
> Could not determine the dependencies of null.
   > SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/alice.barssericordel/spark-android/local.properties'.
```

We need to create a local.properties file containing at least the SDK location.
It might be useful to add this to the README

### Describe the solution

Add this info to the README

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
👋 `local.properties` is an Android Studio auto-generated file. Did you import the project with Android Studio?

**Comment by AliceBarsseLbc** [comment]
Actually no, I wanted to run the sample App, so I used CLI only.

**Comment by AliceBarsseLbc** [comment]
Thanks for the tip :smile: There was no trouble creating the file :lol:
I just wanted to add the info to the README for the project to avoid other
developers wasting their time on this setup stuff
From the git server it seems I can't make a change without a ticket (among
other steps...), so I at least created the ticket

Alice
