### ISSUE TITLE
Setup CI to version and publish the spark artifact

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#4]

**Comment by soulcramer** [comment]
Require #14 before being able to complete this

**Comment by SimonMarquis** [comment]
Implemented by #167 

Example run: https://github.com/adevinta/spark-android/actions/runs/4356746820
Snapshot version is published here: `spark-0.0.0-20230307.171604-2` https://s01.oss.sonatype.org/content/repositories/snapshots/com/adevinta/spark/spark/0.0.0-SNAPSHOT/
And contains a valid signature.
