### ISSUE TITLE
[FR]: Update icons res in the project when icons in spark-tokens project are updated

### ISSUE THREAD

**Issue by MarinaRomanova** [adevinta/spark-android#403]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

[adevinta/spark-tokens](https://github.com/adevinta/spark-tokens) project should be the only source of truth. When icons are updated in that project, [adevinta/spark-android](https://github.com/adevinta/spark-android/) icons should also be updated to contain the latest version of icons.

### Describe the solution

Add a workflow to automate the delivery process of icons to [adevinta/spark-android](https://github.com/adevinta/spark-android/)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
https://github.com/adevinta/spark-tokens/pull/33

**Comment by SimonMarquis** [comment]
The next step (migrating from XML AVD to inlined Compose code) could be automated with this the same tool used by AndroidX Material: https://github.com/androidx/androidx/tree/androidx-main/compose/material/material/icons
