### ISSUE TITLE
[Bug] Checkbox border color is not correct

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark-android#430]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?
The color of the checkbox is not correct.

### Expected
✅ It should be grey as in web: https://sparkui.vercel.app/?path=/docs/components-checkbox--docs#usage

![capture_d___e__cran_2023-06-06_a___15 24 08](https://github.com/adevinta/spark-android/assets/23620759/99e41f90-8905-489c-a2b4-7ae0e3ae241f)

### Problem
🚨 But it's black 

https://github.com/adevinta/spark-android/assets/23620759/7f3ee7fd-814b-4536-9363-085eeb1ed994

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soulcramer** [comment]
After reviewing it with @turolopezsanabria We'll stay with the current version where the enabled unchecked checkbox is black as changing it to outline breaks state hierarchy
