### ISSUE TITLE
[Textfield] The typography looks fatter than expected

### ISSUE THREAD

**Issue by ImeneSediri** [adevinta/spark-android#539]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

Other (please specify it)

### 🐛 What happened?

[AND : The typography still looks fatter than the wireframes (so there's an optical effect, which makes it look squashed). Can you fix it?](https://adevinta.slack.com/archives/C04QQEU3Y2H/p1689844689275919)

![image](https://github.com/adevinta/spark-android/assets/140066753/8a9fb13b-d794-4789-8aac-db76782d6c53)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soulcramer** [comment]
We can't action on it as this is indeed the AA from the device and the capture conversion that cause this blur and makes the typo bolder.

A follow up would be to see if we want to adjust the typo on android to take this into account
