### ISSUE TITLE
[FR]: Chips - all platform

### ISSUE THREAD

**Issue by ImeneSediri** [adevinta/spark-android#542]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

**CHIPS** 
We did user test last few weeks with secondary tinted chips as active and clickable chips, and the users were reluctant to click on the chip. We think the current defaut chips are note enough affordant and doesn't help the user to make the difference between active/default.

[More informations here](https://adevinta.slack.com/archives/C053HR35NTV/p1689670981877839?thread_ts=1688545901.323959&cid=C053HR35NTV)

------
Moreover, in Search feature team, we need a badge into the chips, to the right of the label (where there is sometimes the delete icon). It will use to inform the user about the number of filters he has activated.
<img width="335" alt="image" src="https://github.com/adevinta/spark-android/assets/140066753/73e0f62e-aa31-40c8-abb9-4349e37ebde6">

### Describe the solution

1. The whole LBC UI Team recommends to change the outline color of default chips (replace secondary by outline color), as it's recommended also in Material 3.

2. Improve the chips component, and add a badge to the right of the label

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by turolopezsanabria** [comment]
@JeremiasUX @Bibisirius 
Please check this request. The final decision must be the same in 4 platforms:
for iOS, Android, Web, and Figma

**Comment by JeremiasUX** [comment]
> Improve the chips component, and add a badge to the right of the label

This is currently possible on:

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] Design

**Comment by JeremiasUX** [comment]
This ticket has been answered and will be continued by [[Design Spec] Chip 2. iteration#1273](https://github.com/adevinta/spark/issues/1273)

**Comment by turolopezsanabria** [comment]
> This ticket has been answered and will be continued by [[Design Spec] Chip 2. iteration#1273](https://github.com/adevinta/spark/issues/1273)

Cool, should we close this ticket and continue in the other one?
