### ISSUE TITLE
[Textfield] Select either `onSurface` or `neutral` for plugin content color

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#581]
<table>
<tr>
 <td>Neutral
 <td>OnSurface
<tr>
 <td><img width="1004" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/498a6077-e895-45ca-b38a-6d92f84ebe25">
 <td><img width="1027" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/224129ab-f1ed-4f99-a857-4c3c51d0b230">
</table>

**Comment by turolopezsanabria** [comment]
onSurface please
