### ISSUE TITLE
[Tech] Save theme settings to avoid reseting them on each application start

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#597]
I don't have any clear idea on how to do it but I think a proto Datastore would be a good start like in the NIA app 🤔 

We may consider also adding a VM to the MainActivity and branch the repo to it.

**Comment by soulcramer** [comment]
@elisa-hery there's no specs for this but can you confirm that when you change a parameter from the theme configurator it does get saved when you leave and come back in the app?

**Comment by elisa-hery** [comment]
@soulcramer yayyy it's working 🥳 
I'm moving the ticket to done
