### ISSUE TITLE
[Catalog] Change the name of the Catalog app to not be truncated 

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#603]
Currently the name of the catalog app is `Spark Catalog` but on a device launcher it appears as `Spark Cat…` and as Discussed with @SimonMarquis  we can simply rename it to just `Spark` as we don't have any other app with the name spark it's safe to have this name.

**Comment by SimonMarquis** [comment]
![Screenshot_20230809-084018.png](https://github.com/adevinta/spark-android/assets/1921278/dc1229f1-b591-41dd-ad54-216af5dc5b44)

In french, "cata" is the short form of disaster 😬
