### ISSUE TITLE
[Component] Modal/Dialog

### ISSUE THREAD

**Issue by MarinaRomanova** [adevinta/spark-android#620]
doc - https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=6255-36810&mode=design&t=5bV4wOcTAAfswfxw-0

**Comment by Bibisirius** [comment]
News: We ca remove the padding content if necessary 

Done for the design ✅ : [url](https://github.com/adevinta/spark/issues/777)
