### ISSUE TITLE
Add step to print AAR content on PRs

### ISSUE THREAD

**Issue by SimonMarquis** [adevinta/spark-android#66]
Use [JakeWharton/diffuse](https://github.com/JakeWharton/diffuse) to dump AAR content after a successful build.

```bash
diffuse info --aar spark.aar
```

**Comment by soulcramer** [comment]
Agreed, where would we save the "previous" AAR?

**Comment by SimonMarquis** [comment]
For now it would only be the info of the current AAR.
Diffing is a bit tricky to do right.

**Comment by soulcramer** [comment]
I see, is a good first step if we can set this up now though 👍
