### ISSUE TITLE
[Component] Button - Add missing shapes

### ISSUE THREAD

**Issue by MarinaRomanova** [adevinta/spark-android#661]
https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=2340-22741&mode=design&t=ewtI1kuBXsWtfygy-4
<img width="477" alt="Screenshot 2023-08-23 at 17 27 50" src="https://github.com/adevinta/spark-android/assets/36896406/542e5d22-56c2-49d3-b1b7-6522965a94af">

```[tasklist]
### Tasks
- [x] Button component
- [x] Icon button component
- [x] Icon toggle button component
```

**Comment by elisa-hery** [comment]
All clear ✅ 
There is a white background button / icon button / toggleable button that shouldn't be here, but this will be handled in https://github.com/adevinta/spark-android/pull/767 ( @kazaky )
