### ISSUE TITLE
Outline components must have transparent background [Android]

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark-android#717]
✅ All components must have a background transparent in outline versions
✅ Tabs have a background transparent too

**Task**
- Apply a background `transparent` to all components on rest/enabled 
- Don't change the current styles for hover, active, disabled, focus, etc. The current definition is still valid for the other states  

**Components affected**

- [x] button
- [x] iconButton
- [x] tab
- [x] tag
- [x] chip

**Comment by elisa-hery** [comment]
These components were already transparents in outline versions. @soulcramer checked on them, there isn't any way for now to check transparency on catalog app. 
I'm moving this ticket to done
