### ISSUE TITLE
[Bug] Readonly Textfield now opens the keyboard on tap

### ISSUE THREAD

**Issue by mazzouzi** [adevinta/spark-android#756]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

Other (please specify it)

### 🐛 What happened?

Spark version: 0.5.0

Whenever we tap on a **readonly** Textfield, the Android keyboard appears.

https://github.com/adevinta/spark-android/assets/21988512/8ab5b0fb-83c0-4461-a88e-12762e34ceb3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
Fixed in Compose foundation 1.6.0-alpha03

> Fixed text fields showing keyboard and being editable when readOnly is true. Also fixed the keyboard not showing when readOnly is changed from true to false while focused. ([I34a19](https://android-review.googlesource.com/#/q/I34a19a80d8f44b10f23db0ca0dd7b43b69311c7c), [b/246909589](https://issuetracker.google.com/issues/246909589))
https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.6.0-alpha03

**Comment by SimonMarquis** [comment]
This was backported to 1.5.1 🙌 
https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.5.1

**Comment by soulcramer** [comment]
Since it's backported we can close it 🥳
