### ISSUE TITLE
[Bug]: SparkTextField: NPE Paint.setColor()

### ISSUE THREAD

**Issue by shkschneider** [adevinta/spark-android#766]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?

Crash: NPE on a setColor() on a null Paint.

### Relevant logcat output

```shell
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void androidx.compose.ui.graphics.Paint.setColor-8_81llA(long)' on a null object reference
androidx.compose.foundation.text.TextFieldState.update-fnh65Uc (CoreTextField.kt:933)
androidx.compose.foundation.text.CoreTextFieldKt.CoreTextField (CoreTextField.kt:250)
androidx.compose.foundation.text.BasicTextFieldKt.BasicTextField (BasicTextField.kt:161)
com.adevinta.spark.components.textfields.SparkTextFieldKt$SparkTextField$5.invoke (SparkTextField.kt:212)
com.adevinta.spark.components.textfields.SparkTextFieldKt$SparkTextField$5.invoke (SparkTextField.kt:210)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shkschneider** [comment]
I failed to locate any Paint/setColor usages in SparkTextField.
Maybe this is a Compose bug?

**Comment by soulcramer** [comment]
Seems like not something that can happen by looking at the source. And since we have only one user with this issue I think we can close it as not fixable on our end
