### ISSUE TITLE
[Bug]: IconButtonGhost not displayed properly in a ConstraintLayout

### ISSUE THREAD

**Issue by GoUpNorth** [adevinta/spark-android#773]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?

I'm having a hard time using the IconButtonGhost component in a ConstraintLayout, it looks like the constraints are not applied properly to it.
I don't have any issue when using a Material3 component or the deprecated Spark IconButton.
This code gives the following result.

```
ConstraintLayout(modifier = Modifier.padding(16.dp)) {
    val (title, button, radioButtons) = createRefs()

    Text(
        text = stringResource(R.string.search_chip_listing_choose_view_label),
        style = SparkTheme.typography.headline2,
        modifier = Modifier.constrainAs(title) {
            centerVerticallyTo(button)
        }
    )

    IconButton(
        onClick = dismiss,
        modifier = Modifier.constrainAs(button) {}
    ) {
        Icon(
            sparkIcon = SparkIcons.Close,
            contentDescription = stringResource(id = R.string.searchtoppanel_close),
            size = IconSize.Medium,
        )
    }
    createHorizontalChain(title, button)
}
```
And here is the result I get:
![image](https://github.com/adevinta/spark-android/assets/31015348/7f1cc2ec-92e5-4cbf-b712-64b1c7ecc534)

When using it in a constraint layout, the button doesn't seem to respect the constraints. The code gives the following result.
```
ConstraintLayout(modifier = Modifier.padding(16.dp)) {
    val (title, button, radioButtons) = createRefs()

    Text(
        text = stringResource(R.string.search_chip_listing_choose_view_label),
        style = SparkTheme.typography.headline2,
        modifier = Modifier.constrainAs(title) {
            centerVerticallyTo(button)
        }
    )

    IconButtonGhost(
        icon = SparkIcons.Close,
        onClick = dismiss,
        intent = IconButtonIntent.Neutral,
        contentDescription = stringResource(id = R.string.searchtoppanel_close),
        modifier = Modifier.constrainAs(button) {}
    )
    
    createHorizontalChain(title, button)
}
```
![image](https://github.com/adevinta/spark-android/assets/31015348/0117d720-3dfc-4275-8a53-66d143352551)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soulcramer** [comment]
Okay I think I know why this can happen, when creating this component we pass the `modifier` to the `Surface` instead of the `PlainTooltipBox` that wraps it

![image](https://github.com/adevinta/spark-android/assets/11772084/2ba88b23-d93a-4c90-85d3-bb1f73684864)
