### ISSUE TITLE
[Component] Remove state colors on icons, message and label for TextFields

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#790]

**Comment by soulcramer** [comment]
The ask changes are not applied on Figma, should I wait for them to be applied to be sure I'm will modify the right values? @adevinta/spark-design

**Comment by soulcramer** [comment]
@elisa-hery You can find the before after in the [PR description](https://github.com/adevinta/spark-android/pull/1013)

**Comment by elisa-hery** [comment]
Cool ! 
Who wants to check it on design side @Bibisirius @JeremiasUX ? (available in latest version)

**Comment by Bibisirius** [comment]
@elisa-hery @soulcramer @thomas-leguellec @kazaky 
- Alert textfield: ✅ 
 ![Image](https://github.com/adevinta/spark-android/assets/139967199/88a7376f-72a9-4c3a-82d2-3aa0cc396105)
- Success textfield : ✅ 
 ![Image](https://github.com/adevinta/spark-android/assets/139967199/2891d656-d5a9-4596-9444-418806ec265e)
- Error textfield : ✅ 
 ![Image](https://github.com/adevinta/spark-android/assets/139967199/2906b74f-eec3-4cf6-a0a4-46734fbdce08)


- Can you check that the icon colour is `Neutral` #353741 by default?
![Image](https://github.com/adevinta/spark-android/assets/139967199/bc97c420-645d-40ed-9c55-878d87d664ab)

If so, we're good ✅ 
If not, you'll need to update it
