### ISSUE TITLE
Add Progressbar Configurator

### ISSUE THREAD

**Issue by kazaky** [adevinta/spark-android#865]

**Comment by kazaky** [comment]
hmmm, that's weird :D 

Because for real on my screen it shows all intents, we can have a call tomorrow and check together



![Image](https://github.com/adevinta/spark-android/assets/4202132/c8f925f4-56b5-4a87-9c41-1d477689f723)

**Comment by kazaky** [comment]
@elisa-hery

**Comment by elisa-hery** [comment]
@kazaky it's ok it was just a mistake !
I'm moving this ticket to done 🚀
