### ISSUE TITLE
Add Popover configurator

### ISSUE THREAD

**Issue by kazaky** [adevinta/spark-android#866]
with or without tip
with short / long text in the container (to test scrolling)
alignment left/right/start/end

**Comment by kazaky** [comment]
is the space between popover and button md ? It seems to me that it looked smaller in [the specs]

I will have a look at this one

**Comment by elisa-hery** [comment]
Ok ! Adding your comments here --> https://adevinta.slack.com/archives/C05BWS2K916/p1704880641563189?thread_ts=1704875402.090639&cid=C05BWS2K916

**Comment by elisa-hery** [comment]
@kazaky I've seen your fix, everything is clear --> I'm moving the ticket to RFP ✅
