### ISSUE TITLE
[Bug]: Button Icon End doesn't show on Buttons if it's a multi line button

### ISSUE THREAD

**Issue by kazaky** [adevinta/spark-android#916]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?

A bug happened!
![Screenshot 2024-01-24 at 11 20 51 AM](https://github.com/adevinta/spark-android/assets/4202132/0f1e5876-5688-4f7c-8343-103da7eba5cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soulcramer** [comment]
@elisa-hery You can verify it by using the button configurator before the fix and check that it doesn't happen anymore after it

**Comment by elisa-hery** [comment]
Perfect, thank ! I'm moving it to done 

<img width="547" alt="Capture d’écran 2024-03-06 à 09 51 33" src="https://github.com/adevinta/spark-android/assets/142396647/e4c725bc-1114-4652-8def-8b3cb2fec017">
