### ISSUE TITLE
[FR]: xml parsing in a lint rule for our custom annotations

### ISSUE THREAD

**Issue by kazaky** [adevinta/spark-android#917]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

User would miss spell our custom annotation names like `typography` `large`

### Describe the solution

building a lint rule that will assert that only supported values are used for our keys 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
This Lint rule should also detect and warn about unexpected empty annotations, especially for variable inputs:

Given these examples:
```xml
    <string name="spark_testing_1">Hi <annotation variable="foo"/></string>
    <string name="spark_testing_2">Hi <annotation variable="foo"></annotation></string>
    <string name="spark_testing_3">Hi <annotation variable="foo"> </annotation></string>
    <string name="spark_testing_4">Hi <annotation variable="foo">!</annotation></string>
```

only the last two will be able to "replace" the span content.
