### ISSUE TITLE
[Chip] Add the selected state for the Chip component

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#941]

**Comment by elisa-hery** [comment]
@soulcramer somme questions / remarks : 
1. specs mention that "chips may have no action" but I don't find chip without action in the catalog app (I mean, they all are clickable)
2. I don't understand the "kind" example
3. **when chip is closable but text is too long, the close icon disappear**

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-android/assets/142396647/dc31020e-c035-4449-a10e-7bc6744693f6" width="500px">
</picture>

**Comment by soulcramer** [comment]
1. You're right we should make the chip that is not selectable not clickable if asked.
2. I took the same examples that we can find in the web [storybook](https://sparkui.vercel.app/iframe.html?viewMode=docs&id=components-chip--docs#kind) 
I think these represent <img width="641" alt="image" src="https://github.com/adevinta/spark-android/assets/11772084/f4765bae-0d23-44d2-9689-14acf828ac12"> usages that we can find in the spec & handoff 
3. Nice catch!

**Comment by elisa-hery** [comment]
Slack discussion ongoing : https://adevinta.slack.com/archives/C053HR35NTV/p1713952058367669

**Comment by JeremiasUX** [comment]
Looks good to me! 
- Icon 16x16
- Color is good as well
