### ISSUE TITLE
Git LFS bandwidth quota reached

### ISSUE THREAD

**Issue by SimonMarquis** [adevinta/spark-android#956]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of spark are you using?

1.0.0

### 🐛 What happened?

It seems like the repository reached the 1GiB of free bandwidth quota:

https://github.com/adevinta/spark-android/actions/runs/7858263043/job/21443026807#step:2:1

```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/adevinta/spark-android.git/info/lfs'
```

The documentation explains it here:
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage#bandwidth-quota

We might have to purchase "data packs" :grimacing:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by soulcramer** [comment]
From what I see [here](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/upgrading-git-large-file-storage) a data pack cost 5€/month for 50Gib of data
