### ISSUE TITLE
[Translation] Manage the translation of accessbility wording for KD1

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#958]

**Comment by thomas-leguellec** [comment]
Do the exhaustive list of all the wordings that we need to translate in German.

**Comment by kazaky** [comment]
@thomas-leguellec Should I just prepare them in a document or
We already have a localisation software I can add to it, something like https://lokalise.com/translation-software

@soulcramer Do you have idea?

**Comment by kazaky** [comment]
That's the sheet for the wordings
https://docs.google.com/spreadsheets/d/1zqDvDFrkMeMBgsUJHoxA8P_zZ2zlei13msiaI0zW3cI/edit?usp=sharing

**Comment by thomas-leguellec** [comment]
Meeting today between Turo and CopyWriter

**Comment by turolopezsanabria** [comment]
✅ translations done

**Comment by elisa-hery** [comment]
Seen with @soulcramer : translation is done but not applied on Spark yet. @soulcramer is going to handle the application.
