### ISSUE TITLE
[Component] Popover - Update intent container color

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-android#986]
We provide to add intent container color for popover component 
Figma spec: [url](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=4360-24469&mode=design&t=jlyz0k8CaoQC7vyA-11)

- Main container
- Accent container
- Surface container (default color) 
- Neutral container
- Error container
- Success container
- Alert container
- Basic container
- Support container

![Image](https://github.com/adevinta/spark-android/assets/139967199/8efb7601-5ca8-49fd-8e6a-6a2adea2e1e7)

**Comment by soulcramer** [comment]
The configurator has teh intent customizable but it's not used by the popover

**Comment by elisa-hery** [comment]
@soulcramer : OK for intents ✅  

Question : I just noticed that the popover closes itself after a few seconds but it's not in the specs. Is it normal ? was it like this before? 👀
