### ISSUE TITLE
[Component] Badge outline color

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-android#990]
We change the outline badge color by "Base/Surface" 
Sepc:[ url](https://spark.adevinta.com/1186e1705/p/8711ec-badge/t/06fc01)

![Image](https://github.com/adevinta/spark-android/assets/139967199/a9c64b52-2155-47c2-a51f-7157a5cfaa6a)

**Comment by soulcramer** [comment]
done in version 0.9.0
